
  CREATE TABLE "ADMIN"."INVOICE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CUSTOMERNAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"ISSUEDATE" DATE NOT NULL ENABLE, 
	"DUEDATE" DATE NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(500 BYTE), 
	"INVOICETOTAL" NUMBER, 
	 CONSTRAINT "INVOICE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
